# Generated by Django 5.2.17 on 2026-08-12 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login_success', 'Login successful'), ('login_failed', 'Login failed'), ('new_device_login', 'New device login'), ('password_changed', 'Password changed'), ('password_reset', 'Password reset'), ('email_changed', 'Email changed'), ('two_factor_enabled', 'Two-factor authentication enabled'), ('two_factor_disabled', 'Two-factor authentication disabled'), ('recovery_code_used', 'Recovery code used'), ('session_revoked', 'Session revoked'), ('account_locked', 'Account locked'), ('account_unlocked', 'Account unlocked'), ('account_deactivated', 'Account deactivated'), ('account_deleted', 'Account deleted'), ('api_key_created', 'API key created'), ('api_key_revoked', 'API key revoked')], db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='security_event_user_time_idx')],
            },
        ),
    ]
