# Generated by Django 5.2.17 on 2026-08-12 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottleState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension_hash', models.CharField(max_length=64, unique=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
